### ISSUE TITLE
Part of the code is missing

### ISSUE THREAD

**Issue by YXDZZU** [xiongsiheng/TEILP#1]
I admire your work, but I have some problems reproducing your code. The TEKG_timestamp_acc_ver method in Graph.py does not seem to define '_initialize_probabilities_lists', but the following call
![image](https://github.com/xiongsiheng/TEILP/assets/162699833/7589df09-e182-4269-b120-a79f1e9c62bc)

**Comment by xiongsiheng** [comment]
Since we are refining the code, there might be some discrepancy between different versions. We have fixed the issue now. Please check the latest version. Thanks!
